<?php

namespace App\Console\Commands;

use App\Http\Controllers\DuePlanController;
use App\Models\DuePlan;
use Carbon\Carbon;
use Illuminate\Console\Command;

class AutoGenerateDues extends Command
{
    protected $signature   = 'dues:auto-generate {--dry-run : Gerçekten oluşturmadan hangi planların çalışacağını göster}';
    protected $description = 'auto_generate aktif aidat planları için zamanı gelen aylık aidatları oluşturur.';

    public function handle(DuePlanController $controller): int
    {
        $today  = Carbon::today();
        $period = $today->format('Y-m');

        $plans = DuePlan::query()
            ->where('auto_generate', true)
            ->where('is_active', true)
            ->where('year', $today->year)
            ->get();

        if ($plans->isEmpty()) {
            $this->info('Aktif otomatik aidat planı bulunamadı.');
            return self::SUCCESS;
        }

        foreach ($plans as $plan) {
            if ($today->day < $plan->generate_day) {
                $this->line("[{$plan->name}] Henüz zamanı gelmedi (oluşturma günü: {$plan->generate_day}, bugün: {$today->day}).");
                continue;
            }

            if ($plan->isGeneratedForPeriod($period)) {
                $this->line("[{$plan->name}] {$period} dönemi zaten oluşturulmuş, atlandı.");
                continue;
            }

            if ($this->option('dry-run')) {
                $this->info("[DRY-RUN] [{$plan->name}] {$period} dönemi oluşturulacak.");
                continue;
            }

            $count = $controller->createDuesForPeriod($plan, $period);

            if ($count === 0) {
                $this->warn("[{$plan->name}] {$period} dönemi: Aidatlandırılacak daire bulunamadı.");
            } else {
                $this->info("[{$plan->name}] {$period} dönemi: {$count} daireye aidat oluşturuldu.");
            }
        }

        return self::SUCCESS;
    }
}
